name = "vbi-contact-form"
main = "src/index.js"
compatibility_date = "2026-03-13"
compatibility_flags = ["nodejs_compat"]

[vars]
FROM_EMAIL = "contact@dermobrain.com"
TO_EMAIL = "Naren@ekwa.com"
ALLOWED_ORIGIN = "https://vbi.narenlife.com"
