name = "vbi-newsletter"
main = "src/index.js"
compatibility_date = "2026-03-13"
compatibility_flags = ["nodejs_compat"]

[vars]
FROM_EMAIL = "newsletter@narenlife.com"
ALLOWED_ORIGIN = "https://vbi.narenlife.com"
CONFIRM_URL = "https://vbi-newsletter.naren-ekwa.workers.dev"
